[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install --omit=optional && npm run build"

[build.environment]
  NODE_VERSION = "20.18.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200